// GitHub API helpers for the autonomous pipeline
// Commits feed.json to the repo and manages monitoring Issues

const GH_API = 'https://api.github.com';

function getHeaders() {
    const token = process.env.GITHUB_TOKEN;
    if (!token) throw new Error('GITHUB_TOKEN env var not set');
    return {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
        Accept: 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
    };
}

function getRepo(): string {
    const repo = process.env.GITHUB_REPO;
    if (!repo) throw new Error('GITHUB_REPO env var not set (format: owner/repo)');
    return repo;
}

/** Commit feed.json to the GitHub repo on main branch */
export async function commitFeedJson(content: string): Promise<string> {
    const repo = getRepo();
    const path = 'lede-app/src/data/feed.json';
    const encoded = Buffer.from(content).toString('base64');

    // Get current file SHA (required for updates)
    const shaRes = await fetch(`${GH_API}/repos/${repo}/contents/${path}`, {
        headers: getHeaders(),
    });

    let sha: string | undefined;
    if (shaRes.ok) {
        const data = await shaRes.json() as { sha: string };
        sha = data.sha;
    }

    const now = new Date().toISOString().split('T')[0];
    const body: Record<string, unknown> = {
        message: `🤖 auto: daily feed refresh ${now}`,
        content: encoded,
        branch: 'main',
    };
    if (sha) body.sha = sha;

    const res = await fetch(`${GH_API}/repos/${repo}/contents/${path}`, {
        method: 'PUT',
        headers: getHeaders(),
        body: JSON.stringify(body),
    });

    if (!res.ok) {
        const err = await res.text();
        throw new Error(`GitHub commit failed (${res.status}): ${err}`);
    }

    const data = await res.json() as { commit: { sha: string } };
    return data.commit.sha;
}

/** Open a GitHub Issue to alert about a pipeline failure */
export async function openPipelineIssue(errorMsg: string, runId: string): Promise<string> {
    const repo = getRepo();
    const date = new Date().toISOString().split('T')[0];

    const body = await fetch(`${GH_API}/repos/${repo}/issues`, {
        method: 'POST',
        headers: getHeaders(),
        body: JSON.stringify({
            title: `🚨 Pipeline failed — ${date}`,
            body: `## Autonomous Pipeline Failure\n\n**Run ID:** \`${runId}\`\n**Date:** ${date}\n\n### Error\n\`\`\`\n${errorMsg}\n\`\`\`\n\n---\nThis issue was opened automatically by the Lede.nyc pipeline monitor.\nAssign to Copilot for investigation or fix manually and close.`,
            labels: ['pipeline', 'automated', 'bug'],
        }),
    });

    if (!body.ok) throw new Error(`Failed to open GitHub Issue: ${body.status}`);
    const data = await body.json() as { html_url: string; number: number };
    return data.html_url;
}

/** Close any open pipeline issues when a successful run occurs */
export async function closePipelineIssues(): Promise<void> {
    const repo = getRepo();

    // List open issues with 'pipeline' label
    const res = await fetch(
        `${GH_API}/repos/${repo}/issues?labels=pipeline%2Cautomated&state=open&per_page=10`,
        { headers: getHeaders() },
    );
    if (!res.ok) return;

    const issues = await res.json() as Array<{ number: number }>;

    await Promise.all(issues.map(issue =>
        fetch(`${GH_API}/repos/${repo}/issues/${issue.number}`, {
            method: 'PATCH',
            headers: getHeaders(),
            body: JSON.stringify({
                state: 'closed',
                state_reason: 'completed',
                body_suffix: '✅ Resolved automatically — pipeline is healthy again.',
            }),
        }),
    ));
}

/** Ensure pipeline/automated labels exist in the repo */
export async function ensureLabels(): Promise<void> {
    const repo = getRepo();
    const labels = [
        { name: 'pipeline', color: '0075ca', description: 'Autonomous pipeline issues' },
        { name: 'automated', color: 'e4e669', description: 'Auto-generated by pipeline monitor' },
    ];
    await Promise.all(labels.map(label =>
        fetch(`${GH_API}/repos/${repo}/labels`, {
            method: 'POST',
            headers: getHeaders(),
            body: JSON.stringify(label),
        }).catch(() => { /* label may already exist */ }),
    ));
}
